---
title: Introduction to Engineering Mathematics
author: Prof. Joris Vankerschaver
format: html
---

## Presentations

- [1 - Trigonometry (1/5): Introduction](presentations/01a-trigonometry-basic-identities.qmd)
- [1 - Trigonometry (2/5): Formulas](presentations/01b-trigonometry-formulas.qmd)
- [1 - Trigonometry (3/5): Geometry of triangles](presentations/01c-trigonometry-triangles.qmd)
- [1 - Trigonometry (4/5): Trigonometric equations](presentations/01d-trigonometry-trigonometric-eqns.qmd)
- [1 - Trigonometry (5/5): Inverse trigonometric functions](presentations/01e-trigonometry-inverse-functions.qmd)
- [2 - Coordinate Geometry](presentations/02-coordinate-geometry.qmd)
- [3 - Limits and Continuity (1/2)](presentations/03a-limits-continuity.qmd)
- [3 - Limits and Continuity (2/2)](presentations/03b-limits-continuity.qmd)
- [4 - Derivatives (1/2)](presentations/04a-derivatives.qmd)
- [4 - Derivatives (2/2)](presentations/04b-derivatives.qmd)
- [5 - Complex Numbers](presentations/05-complex-numbers.qmd)
- [6 - Polynomials (1/2)](presentations/06a-polynomials.qmd)
- [6 - Polynomials (2/2)](presentations/06b-polynomials.qmd)
- [7 - The Binomial Theorem](presentations/07-binomial-theorem.qmd)
- [8 - Integration: Definitions](presentations/08a-integration-definitions.qmd)
- [8 - Integration: Techniques](presentations/08b-integration-techniques.qmd)
- [8 - Integration: Partial Fractions](presentations/08c-integration-partial-fractions.qmd)
- [8 - Integration: Inverse Trigonometric Substitutions](presentations/08d-integration-inverse-trig.qmd)
- [8 - Integration: Applications](presentations/08e-integration-applications.qmd)
- [9 - Proof Techniques](presentations/09-proof-techniques.qmd)



