---
title: "Trigonometry: Trigonometric Equations"
subtitle: Introduction to Engineering Mathematics
author: Prof. Joris Vankerschaver
format:
  revealjs:
    theme: [default, custom.scss]
    slide-number: true
    css: style.css
---

## Overview

1. Word problems: solutions
2. Trigonometric equations

## Word problem 1 {.smaller}

You see a town on a hillside at an angle of elevation of 30째. You walk 80 meters (horizontally, along the ground) and see the town at an angle of elevation of 60째. Find the height of the town above ground level.

## Word problem 2 {.smaller}

A man lies on the ground and observes that a temple and a flagpole on that temple subtend equal angles at his eyes. If the height of the temple is 10m and that of the flagpole is 20m, find the subtended angles and the distance between the temple and the man.

## Word problem 3 {.smaller}

Crown Prince Lee Chang stands on the fortress walls and overlooks an approaching zombie army. He observes a zombie under an angle of depression of 45째 and shoots an arrow. One second later, he shoots an arrow at the same zombie under an angle of depression of 60째. How soon will the zombie reach the base of the wall?
