---
title: Limits and Continuity (2/2)
subtitle: Introduction to Engineering Mathematics
author: Prof. Joris Vankerschaver
format:
  beamer:
    theme: Pittsburgh
    colortheme: default
    fonttheme: default
    include-in-header:
      - file: header.tex

classoption: t
---

## Contents

\tableofcontents

## Infinite limits

We say that $f(x)$ has an **infinite limit** for $x \to a$ if the values of $f(x)$ become **arbitrarily large** when $x \to a$.

We note
$$
  \lim_{x \to a} f(x) = \infty \quad \text{or} \quad \lim_{x \to a}f(x) = -\infty,
$$
depending on the sign of $f(x)$ near $x = a$.

Examples:

- $\displaystyle \lim_{x\to 0}\frac{1}{x^2}$
- $\displaystyle \lim_{x\to 0+} \ln x$

## Vertical asymptotes

The line $x = a$ is a **vertical asymptote** of $f(x)$ if *at least one* of the following is true:
$$
  \lim_{x \to a+} f(x) = \pm\infty \quad \text{or} \quad \lim_{x \to a-}f(x) = \pm\infty.
$$

Example: find the vertical asymptotes of

- $\displaystyle y = \ln x$
- $\displaystyle y = \tan x$

## Example

Find all vertical asymptotes of the function 
$$
  f(x) = \frac{|x-1|}{x^2-3x+2}.
$$

Hint: *Look for zeros of the denominator that are not zeros of the numerator.*

## Limits at infinity (intuition)

What happens to $f(x)$ when $x$ becomes very large (positive/negative)?

Examples:

- $\displaystyle \lim_{x \to \pm \infty} \frac{x^2 - 1}{x^2 + 1}$
- $\displaystyle \lim_{x \to +\infty}e^{-x}$

## Limits at infinity (definition)

We write:

:::: {.columns}
::: {.column width="48%"}
$$
    \lim_{x \to +\infty} f(x) = L
$$

:::
::: {.column width="4%"}
:::
::: {.column width="48%"}
$$
     \lim_{x \to -\infty}f(x) = M
$$
:::
::::

We mean:


:::: {.columns}
::: {.column width="48%"}
- $f(x)$ is defined on an interval $(a, +\infty)$
- $f(x)$ gets as close as we want to $L$ by taking $x$ large enough.

:::
::: {.column width="4%"}
:::
::: {.column width="48%"}

- $f(x)$ is defined on an interval $(-\infty, b)$
- $f(x)$ gets as close as we want to $M$ by taking $x$ large enough (in the negative direction).

:::
::::

## Horizontal asymptotes

The line $y = L$ is a **horizontal asymptote** of $f(x)$ if *at least one* of the following is true:
$$
    \lim_{x \to +\infty}f(x) = L \quad \text{or} \lim_{x \to -\infty}f(x) = L.
$$

Examples: Find the horizontal asymptotes of

- $\displaystyle y = \frac{x^2 - 1}{x^2 + 1}$
- $\displaystyle y = e^{-x}$
- $\displaystyle y = \frac{e^x - e^{-x}}{e^x + e^{-x}}$

## Limit laws

1. $\lim_{x \to \infty} x = \infty$
2. $\lim_{x \to \infty} c = c$ (for $c$ a constant)
3. $\lim_{x \to \infty}(f(x) + g(x)) = \lim_{x \to \infty} f(x) + \lim_{x \to \infty} g(x)$
4. $\lim_{x \to \infty} (cf(x)) = c\lim_{x \to \infty} f(x)$
5. $\lim_{x \to \infty}(f(x)g(x)) = \lim_{x \to \infty} f(x) \lim_{x \to \infty} g(x)$
6. $\lim_{x \to \infty} \frac{f(x)}{g(x)} = \frac{\lim_{x \to \infty} f(x)}{\lim_{x \to \infty} g(x)}$, if the denominator is not zero

## Limit laws (continued)
7. $\lim_{x \to \infty} f(x)^{m/n} = \left(\lim_{x \to \infty} f(x) \right)^{m/n} = L^{m/n}$, if
   - $L \ge 0$ for $n$ even
   - $L \ne 0$ for $m$ negative
8. If $f(x) \le g(x)$, then $\lim_{x \to \infty} f(x) \le \lim_{x \to \infty} g(x)$
9. $\lim_{x \to \infty} 1/x^n = 0$, if $n > 0$
10. $\lim_{x \to \infty} g(f(x)) = \lim_{y \to c} g(y)$, where $c = \lim_{x\to \infty}f(x)$, if
    - $c$ is constant (not equal to $\pm \infty$)
    - $f$ is continuous (see later)
    
## Examples    

$\displaystyle \lim_{x \to +\infty} \frac{2x^5 + 1}{x^5 + x^3 + 1}$  

## Examples    

$\displaystyle \lim_{x\to -\infty} \frac{x^7}{\sqrt{x^{14} + 1}}$

## Examples    

$\displaystyle \lim_{x \to +\infty}\left( \sqrt{x^2 + 1} - x \right)$

## Examples    

$\displaystyle \lim_{x\to 0-} e^{1/x}$

## Examples    

$\displaystyle \lim_{x\to +\infty} \sin x$

## Examples

$\displaystyle \lim_{x \to \pi/2-} e^{\tan x}$

## Infinite limits at infinity

Examples:

## Summary of limit techniques

1. Try "just substituting" $\pm\infty$
2. Use common manipulations:
   - Simplify
   - Highest powers
   - Conjugate
   - ...

## Special cases (to memorize):
$$
    \lim_{h \to 0}\frac{\sin h}{h}  = 1 \quad \text{and} \quad
    \lim_{h \to 0}\frac{\cos h - 1}{h}  = 0.
$$
   
## Continuity

- Intuitively, continuity $=$ "no jumps"
- Mathematically, $f(x)$ is **continuous** at an interior point $x = a$ of its domain if
$$
  \lim_{x \to a} f(x) = f(a).
$$  

Example: $\displaystyle f(x) = \frac{x^2 - x - 3}{x - 2}$ is not continuous at $x = 2$.

## Examples

Define $f(x) = \frac{x^2 - x - 2}{x - 2}$ when $x \ne 2$ and $f(x) = 1$ otherwise (i.e. $f(2) = 1$). Is $f(x)$ continuous at $x = 2$?

## Left/right continuity

At $x = a$, $f(x)$ is ...

- **Right continuous** if $\displaystyle \lim_{x\to a+} f(x) = f(a)$
- **Left continuous** if $\displaystyle \lim_{x\to a-} f(x) = f(a)$.

Example: the Heaviside function is defined by $H(x) = 0$ when $x < 0$ and $H(x) = 1$ when $x \ge 0$. Is $H(x)$ right or left continuous at $x = 0$?

## Continuity on an interval

The function $f(x)$ is continuous on an interval $[a, b]$ if ...

- $f(x)$ is continuous at every $x \in (a, b)$
- $f(x)$ is right-continuous in $a$
- $f(x)$ is left-continuous in $b$.

Example: Show that $f(x) = 1 - \sqrt{1 - x^2}$ is continuous on $[-1, 1]$.

## Making new continuous functions out of old ones

If $f(x), g(x)$ are continuous at $x = a$, and $c$ is a constant, then the following are also continuous at $x = a$:

- $f + g$
- $f - g$
- $cf$
- $fg$ 
- $f/g$  (if $g(a) \ne 0$)


## Which functions are continuous?

Continuous **on their domain**:

- Polynomials
- Rational functions
- Trigonometric functions + inverse trigonometric functions
- Square roots, $n$th roots
- $\log$, $\exp$

In particular:

- Polynomials are continuous for all $x \in \mathbb{R}$
- Rational functions $P(x)/Q(x)$ are continuous for all $x$ so that $Q(x) \ne 0$.

## Composition of functions

If $f(x)$ is continuous and $\lim_{x \to a} g(x) = b$, then
$$
    \lim_{x \to a} f(g(x)) = f(b) = f\left( \lim_{x \to a} g(x) \right).
$$

Example: $\displaystyle \lim_{x \to 2} \sin\left( \frac{2-x}{4-x^2}\pi\right)$

## Corollary

If $g$ is continuous at $x = a$ and $f$ is continuous at $y = g(a)$, then $f \circ g$ is continuous at $x = a$.

Examples: Where are the following functions continuous?

- $\displaystyle h(x) = \sin x^2$
- $\displaystyle h(x) = \ln(1 + \cos x)$
