---
title: "Integration: Inverse trigonometric substitution"
subtitle: Introduction to Engineering Mathematics
author: Prof. Joris Vankerschaver
format:
  beamer:
    theme: Pittsburgh
    colortheme: default
    fonttheme: default
    include-in-header:
      - file: header.tex

classoption: t
---

## Contents

\tableofcontents

# Inverse trigonometric substitution

## What is inverse trigonometric substitution?

- Direct substitution: replace part of the integrand by a new variable
- Inverse substitution: **replace variable by new function**.

Example: $\displaystyle \int \sqrt{1 - x^2} dx$ with the substitution $x = \cos \theta$

## Why is this useful?

Inverse trigonometric substitution can solve integrals that have a power of $x^2 \pm a^2$ somewhere in the integrand.

Example:

- $\displaystyle \int \frac{dx}{(x^2 - 25)^3}$
- $\displaystyle \int \sqrt{1 + x^2} dx$

## Types of substitutions

The exact substitution depends on the integrand. We will distinguish the following three cases, depending on factors that occur in the integrand.

1. Factor $\sqrt{a^2 - x^2}$: use $x = a \sin \theta$
2. Factor $\sqrt{a^2 + x^2}$: use $x = a \tan \theta$
3. Factor $\sqrt{x^2 - a^2}$: use $x = a \sec \theta$

Don't memorize these substitutions: use your insight into trigonometry to think what substitution would simplify the integrand.

## Remark: completing the square

Often the integrand will not exactly be in one of the three previous forms. In that case, **completing the square** may help:
$$
    \int \frac{dx}{x^2 + 4x + 5} = \int \frac{dx}{(x + 2)^2 + 1} = \int \frac{dt}{t^2 + 1} = \ldots
$$

## Case 1: $\sqrt{a^2 - x^2}$

- Substitution: $x = a \sin \theta$, with $\theta \in [-\pi/2, \pi/2]$
- Differential: $dx = a \cos \theta \, d \theta$

Example: $\displaystyle \int \frac{dx}{(5 - x^2)^{3/2}}$

## Case 2: $\sqrt{a^2 + x^2}$

- Substitution: $x = a \tan \theta$, with $\theta \in (-\pi/2, \pi/2)$
- Differential: $dx = a \sec^2 \theta \, d \theta$

Example: $\displaystyle \int \frac{dx}{\sqrt{1 + 4x^2}}$

## Case 3: $\sqrt{x^2 - a^2}$

- Substitution: $x = a \sec \theta$, with $\theta \in (0, \pi)$ (**two cases**)
- Differential: $dx = a \tan \theta \sec \theta \, d \theta$

Example: $\displaystyle \int \frac{dx}{\sqrt{x^2 - a^2}}$

# Other substitutions

## Higher root substitutions

### Higher roots

Useful when the integrand has a factor $\sqrt[n]{ax + b}$.

- Substitution: $ax + b = u^n$
- Differential: $a \, dx = n u^{n-1} \, du$

Example: $\displaystyle \int_{-1/3}^2 \frac{x\, dx}{\sqrt[3]{3x+2}}$

## Example

Sometimes this rule can be applied to integrands that are somewhat more general than what's shown on the previous slide.

Example: $\displaystyle \int \frac{dx}{x^{1/2}(1 + x^{1/3})} = \ldots$

(Substitute $x^{1/6} = u$)

## T-formulas

### $\tan \frac{\theta}{2}$-substitution

Useful when the integrand is a rational function of $\sin \theta$ and $\cos \theta$.

- Substitution: $t = \tan \frac{\theta}{2}$, so that $\theta = 2\tan^{-1}(t)$
- Differential: 
$$
d \theta = \frac{2 dt}{1 + t^2}
$$
- $t$-formulas:
$$
    \sin \theta = \frac{2t}{1+t^2} \quad \text{and} \quad \cos \theta = \frac{1 - t^2}{1 + t^2}.
$$

## Example

$\displaystyle \int \frac{d \theta}{2 + \cos \theta} = \ldots$
