.PHONY: all

%.pdf: %.qmd
	quarto render $<

all: 01a-trigonometry-basic-identities.pdf 01b-trigonometry-formulas.pdf 01c-trigonometry-triangles.pdf 01d-trigonometry-trigonometric-eqns.pdf 01e-trigonometry-inverse-functions.pdf 02-coordinate-geometry.pdf 03a-limits-continuity.pdf 03b-limits-continuity.pdf 04a-derivatives.pdf 04b-derivatives.pdf 05-complex-numbers.pdf 06a-polynomials.pdf 06b-polynomials.pdf  07-binomial-theorem.pdf 08a-integration-definitions.pdf 08b-integration-techniques.pdf 08c-integration-partial-fractions.pdf 08d-integration-inverse-trig.pdf 08e-integration-applications.pdf 09-proof-techniques.pdf
